export const AUT_SET_SOURCE_CRS = 'AUT_SET_SOURCE_CRS';
export const AUT_SET_SOURCE_FRAME = 'AUT_SET_SOURCE_FRAME';
export const AUT_SET_SOURCE_ELLPS = 'AUT_SET_SOURCE_ELLPS';
export const AUT_SET_SOURCE_MRDN = 'AUT_SET_SOURCE_MERIDIAN';
export const AUT_SET_SOURCE_CR = 'AUT_SET_SOURCE_COORDINATE_REPRESENTATION';
export const AUT_SET_SOURCE_PRJ = 'AUT_SET_SOURCE_PROJECTION';
export const AUT_SET_SOURCE_HS = 'AUT_SET_SOURCE_HEIGHT_SYSTEM';

export const AUT_SET_TARGET_CRS = 'AUT_SET_TARGET_CRS';
export const AUT_SET_TARGET_FRAME = 'AUT_SET_TARGET_FRAME';
export const AUT_SET_TARGET_ELLPS = 'AUT_SET_TARGET_ELLPS';
export const AUT_SET_TARGET_MRDN = 'AUT_SET_TARGET_MERIDIAN';
export const AUT_SET_TARGET_CR = 'AUT_SET_TARGET_COORDINATE_REPRESENTATION';
export const AUT_SET_TARGET_PRJ = 'AUT_SET_TARGET_PROJECTION';
export const AUT_SET_TARGET_HS = 'AUT_SET_TARGET_HEIGHT_SYSTEM';

export const AUT_SET_HT = 'AUT_SET_HORIZONTAL_TRANSFORMATION';

export const ADD_GEOCENTRIC_POINT = 'ADD_GEOCENTRIC_POINT';
export const REM_GEOCENTRIC_POINT = 'REM_GEOCENTRIC_POINT';
export const ADD_GEOGRAPHIC_POINT = 'ADD_GEOGRAPHIC_POINT';
export const REM_GEOGRAPHIC_POINT = 'REM_GEOGRAPHIC_POINT';
export const ADD_PROJECTED_POINT = 'ADD_PROJECTED_POINT';
export const REM_PROJECTED_POINT = 'REM_PROJECTED_POINT';

export const ADV_SET_SOURCE_FRM = 'ADV_SET_SOURCE_FRM';
export const ADV_SET_SOURCE_EPOCH = 'ADV_SET_SOURCE_EPOCH';
export const ADV_SET_SOURCE_CR = 'ADV_SET_SOURCE_COORDINATE_REPRESENTATION';
export const ADV_SET_SOURCE_PRJ = 'ADV_SET_SOURCE_PROJECTION';
export const ADV_SET_SOURCE_HS = 'ADV_SET_SOURCE_HEIGHT_SYSTEM';
export const ADV_SET_SOURCE_ELL = 'ADV_SET_SOURCE_ELLIPSOID';
export const ADV_SET_SOURCE_MRD = 'ADV_SET_SOURCE_MERIDIAN';

export const ADV_SET_TARGET_FRM = 'ADV_SET_TARGET_FRM';
export const ADV_SET_TARGET_EPOCH = 'ADV_SET_TARGET_EPOCH';
export const ADV_SET_TARGET_CR = 'ADV_SET_TARGET_COORDINATE_REPRESENTATION';
export const ADV_SET_TARGET_PRJ = 'ADV_SET_TARGET_PROJECTION';
export const ADV_SET_TARGET_HS = 'ADV_SET_TARGET_HEIGHT_SYSTEM';
export const ADV_SET_TARGET_ELL = 'ADV_SET_TARGET_ELLIPSOID';
export const ADV_SET_TARGET_MRD = 'ADV_SET_TARGET_MERIDIAN';

export const API_GET_FRAME_LIST = 'API_GET_FRAME_LIST';
export const API_GET_ELLIPSOID_LIST = 'API_GET_ELLIPSOID_LIST';
export const API_GET_MERIDIAN_LIST = 'API_GET_MERIDIAN_LIST';
export const API_GET_PROJECTION_LIST = 'API_GET_PROJECTION_LIST';