export const AUT_SET_SOURCE_CRS = 'AUT_SET_SOURCE_CRS';
export const AUT_SET_SOURCE_CR = 'AUT_SET_SOURCE_COORDINATE_REPRESENTATION';
export const AUT_SET_SOURCE_PRJ = 'AUT_SET_SOURCE_PROJECTION';
export const AUT_SET_SOURCE_HS = 'AUT_SET_SOURCE_HEIGHT_SYSTEM';

export const AUT_SET_TARGET_CRS = 'AUT_SET_TARGET_CRS';
export const AUT_SET_TARGET_CR = 'AUT_SET_TARGET_COORDINATE_REPRESENTATION';
export const AUT_SET_TARGET_PRJ = 'AUT_SET_TARGET_PROJECTION';
export const AUT_SET_TARGET_HS = 'AUT_SET_TARGET_HEIGHT_SYSTEM';

export const AUT_SET_HT = 'AUT_SET_HORIZONTAL_TRANSFORMATION';

export const ADD_GEOCENTRIC_POINT = 'ADD_GEOCENTRIC_POINT';
export const REM_GEOCENTRIC_POINT = 'REM_GEOCENTRIC_POINT';
export const ADD_GEOGRAPHIC_POINT = 'ADD_GEOGRAPHIC_POINT';
export const REM_GEOGRAPHIC_POINT = 'REM_GEOGRAPHIC_POINT';
export const ADD_PROJECTED_POINT = 'ADD_PROJECTED_POINT';
export const REM_PROJECTED_POINT = 'REM_PROJECTED_POINT';
